### ISSUE TITLE
[Question] how to programatically get the metric values

### ISSUE THREAD

**Issue by aguerrieri** [weyoss/redis-smq#39] opened 2020-06-02 19:40 UTC
I am trying to create alerts and/or display queue size in our internal monitoring/alerting/dashboard system. Is there any way to get the metrics from the queues other than through the monitoring web site?

**Comment by weyoss** [comment] 2020-06-08 22:59
Duplicate of #32

**Comment by weyoss** [comment] 2020-06-08 23:04
You should make use of real-time metrics which are provided through WebSocket.

**Closed** 2020-07-02 12:59 UTC
Labels: question / feature request
