### ISSUE TITLE
getting with producer

### ISSUE THREAD

**Issue by ayyappaappana** [weyoss/redis-smq#2] opened 2017-11-24 02:21 UTC
/home/aappana/nodejs/node_modules/redis-smq/src/monitor/index.js:33
            app.use(async (ctx) => {
                          ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/aappana/nodejs/node_modules/redis-smq/index.js:5:17)

Ran this in linux - As this library doesnot support windows. your project architecture was good. but failed.

**Comment by weyoss** [comment] 2017-11-27 12:06
> Ran this in linux - As this library doesnot support windows.
It's not because you had a problem with npm while installing this package and without giving any accurate details about your package.json file or anything else needed to figure out the problem that you can argue confidently that is package does not support windows. See https://github.com/weyoss/redis-smq/issues/1 for more details.

>  your project architecture was good. but failed
First of all if you find that this project is not good to you or does not solve your problem, you are free to use any other convenient package. If you have an issue please provide enough details to reproduce it. Otherwise no support can be provided. 

The issue you reported can not be either verified or reproduced.

**Comment by weyoss** [comment] 2017-12-03 20:35
Closing as abandoned.

**Closed by weyoss** 2017-12-03 20:35 UTC
