### ISSUE TITLE
How we can handle monitorServer listening callback error ?

### ISSUE THREAD

**Issue by cuongnv-ibl** [weyoss/redis-smq#19] opened 2018-07-04 10:59 UTC
if redis server doesn't start, run `monitorServer.listen()` will get app crash

**Comment by weyoss** [comment] 2018-07-04 11:41
```javascript
monitorServer.listen(() => {
    console.log('Monitor server is running...');
});
```
The callback function here is just to inform you that the HTTP server has been started and listening for connections.

Furthermore, If for some reason the monitor could not connect to the Redis server, an error will be thrown and the monitor component will crash because the monitor can not function without a working connection to the Redis server.

There is no need to handle monitor errors.  By design fatal errors will be thrown and will cause the monitor to crash.

**Comment by weyoss** [comment] 2018-07-05 06:15
Closing as resolved.

**Closed by weyoss** 2018-07-05 06:15 UTC
Labels: question / feature request

**Comment by cuongnv-ibl** [comment] 2018-07-05 06:52
Thanks, for explanation , just curiously why by design monitor crash when could not connect?
Is it possible let `monitor` handle attempt reconnect from`retry_strategy` config to Redis

**Comment by weyoss** [comment] 2018-07-07 08:40
The monitor does not in no way process, overwrite or ignore any Redis parameter. 

The Redis parameters are handled by the Redis client. 

`retry_strategy` as you said is a Redis client parameter and it will be handled by the Redis client and when provided, the Redis client, not the monitor, will try to reconnect to Redis according to the strategy.

So to sum up, all Redis client parameters are supported as well as `retry_strategy`.
