### ISSUE TITLE
check remaining jobs

### ISSUE THREAD

**Issue by ramymabrouk** [weyoss/redis-smq#6] opened 2018-02-26 18:08 UTC
hi,
what is the best way to check if the que is not empty? should i create a socketio client like the one in monitor GUI?

**Comment by weyoss** [comment] 2018-02-28 09:33
Hi. I wonder why you need to check if the queue is not empty? I believe for most cases, if not for all cases, in which this application can be used, it is not needed to do so. You just launch a consumer and wait for messages. This can be seen as Pub/Sub except the messages are delivered only once to one consumer at a time. 
For monitoring purposes, the size of all queues  existing in the message queue is provided and updated in "real-time". RedisSMQ provides a simple monitor tool which make use of all the data provided through WebSocket to provide a clear state about the message queue. If you want to use your own monitoring tool, yes you need to use a socketio client.

**Comment by ramymabrouk** [comment] 2018-02-28 12:51
Hi, I need the producer to wait for the queued tasks to finish before i add new set of tasks according to some business needs.

**Comment by weyoss** [comment] 2018-03-02 06:21
By design the API does not provide such method to monitor the actual queue size. I think the same is true for RabbitMQ. You can get the queue size only from stats. You should consider to implement your complicated logic in your app or to use another message queue which provides such mechanism.

**Comment by weyoss** [comment] 2018-03-12 08:38
Closing as resolved.

**Closed by weyoss** 2018-03-12 08:38 UTC
