### ISSUE TITLE
Any chance of updating Redis to v4

### ISSUE THREAD

**Issue by chris-elmstone** [weyoss/redis-smq#78] opened 2022-03-09 11:57 UTC
Hello

The latest version of Redis allows for Promises and is a much nicer way of working, at the moment we use Handi-Redis to bypass this as using Redis 4 conflicts with this package's Redis 3.*.

I will look forward to your reply

Best Regards
Chris

**Comment by weyoss** [comment] 2022-03-10 15:12
@chris-elmstone Thank you for opening this issue.

> we use Handi-Redis to bypass this as using Redis 4 conflicts with this package's Redis 3.*.

Please provide an example to reproduce your conflicts.

I believe you should not have any issue when using a different redis version than the one that this library is using (thanks to NPM dependency resolution algorithm).

Here I am using redis@4.0.4:

```json
{
  "dependencies": {
    "redis": "^4.0.4",
    "redis-smq": "^6.2.6"
  }
}
```

No conflict errors are expected when running this code: 

```typescript
import { Consumer } from 'redis-smq';
import { createClient } from 'redis';

const c = new Consumer();
c.run(() => {
    const r = createClient();
    r.connect().then(() => r.info()).then((i) => {
        console.log(i);
    });
});
```

**Comment by weyoss** [comment] 2022-03-22 17:09
Closing as resolved

**Comment by weyoss** [comment] 2022-05-23 08:30
@PhilHannent I have re-opened this issue as it seems that there is a conflict problem that does not always occur.

Please provide a full working example to reproduce your issue.

You can try to run code from  my previous comment https://github.com/weyoss/redis-smq/issues/78#issuecomment-1064167597

**Comment by weyoss** [comment] 2022-05-23 08:51
The explanation is obvious. When a module is being used in different libraries, NPM handles this situation depending on the following cases:

1. If the module version is the same between all the modules, then the module is shared between all libraries and installed in the main `node_modules` directory.
2. If the module version is NOT the same (in our case redis v4 and v3) between some libraries then each library uses its own module version and the module is installed in a local `node_modules` directory of the library.

![Screenshot_2022-05-23_09-40-10](https://user-images.githubusercontent.com/25721917/169780468-f317b198-3ec6-4f4a-8e1c-21252d17810a.png)

**Comment by PhilHannent** [comment] 2022-05-23 09:00
Good morning weyoss!

To clarify, having the two side by side isn't the issue. It is where we are attempting to have one configuration for both our redis usage and for redis-smq. Because there is a difference in how the redis versions structure their configuration, it seems like we cannot re-use the same structure.

I'll create a small example.

**Comment by weyoss** [comment] 2022-05-23 09:23
Before redis is upgraded to v4, the only solution is to use a separate redis configuration for `redis-smq`.

Please follow https://github.com/weyoss/redis-smq/issues/86 to stay tuned about upgrading to redis@v4

**Closed** 2022-05-23 09:26 UTC
Labels: question
