### ISSUE TITLE
two instances

### ISSUE THREAD

**Issue by fernandodevelon** [weyoss/redis-smq#84] opened 2022-04-26 09:08 UTC
is it possible to have 2 running consumer instances connected to 2 different redis servers ?

**Comment by weyoss** [comment] 2022-05-02 09:35
As far as Redis servers share the **same database** you can connect to any server.

**Comment by weyoss** [comment] 2022-05-02 10:11
Let me make it more clear.

In practical terms, it depends on your setup. You may be either using Redis cluster or Redis Sentinel.

**Redis Sentinel**

It is a HA solution which consists of a master and one or more slaves. Whenever the master goes down, a slave, from the pool, is promoted as a new master.

See [https://github.com/luin/ioredis#sentinel](https://github.com/luin/ioredis#sentinel).

**Redis Cluster**

It is a solution which allows you to distribute your data among multiple Redis servers. Think of it as a multi-master setup.

See [https://github.com/luin/ioredis#cluster](https://github.com/luin/ioredis#cluster).

**Comment by fernandodevelon** [comment] 2022-05-02 10:14
I apologize, maybe I didn't explain myself well.
I would like to connect to the REDIS A server, where it publishes messages, and connect to the REDIS B server, where it consumes messages.

the two REDIS servers are disconnected from each other, and the queues are different, for different functions.

**Comment by weyoss** [comment] 2022-05-02 10:34
So in such case, your application is going to consume and publish messages from/to different systems where each system has its own RedisSMQ running.

It the same thing as connecting to and using two different databases.

Yes, you can do it.

**Comment by fernandodevelon** [comment] 2022-05-02 12:08
I don't understand how considering that the connection configuration is system-wide

**Comment by weyoss** [comment] 2022-05-02 13:00
By design, RedisSMQ configuration is system-wide and within the same process you can not use different configurations.

As a workaround you may consider forking different threads.

**Comment by fernandodevelon** [comment] 2022-05-02 18:40
ok thanks, but for the project is too complex and expensive as implementation.
it would be nice to be able to pass in the class construct a redis connection to use

**Comment by weyoss** [comment] 2022-05-02 19:52
Closing as resolved.

**Closed by weyoss** 2022-05-02 19:52 UTC
Labels: question
