### ISSUE TITLE
Produce messages for multiple queues

### ISSUE THREAD

**Issue by PhantomRay** [weyoss/redis-smq#58] opened 2021-12-21 06:33 UTC
Hi there, 
In my use case, I have to send the same message to a large number of queues. By using `Producer` class, I will have to create multiple instances of producers for multiple queues.

What's the more efficient way to do this? e.g. can we have something like `producer.produce(queue, message, cb)`?

Thanks.

**Comment by weyoss** [comment] 2021-12-21 08:13
@PhantomRay Thank you for opening this issue!

Currently the logic behind the producer is queue-centric and by design each producer can be associated and related only to one queue. 

But I think there can be some cases, such as yours, where we need to publish the same message to many queues.

I believe your suggestion for `producer.produce(queue, message, cb)` is worth to be included in the next release roadmap in order to publish efficiently a message to multiple queues.

I will keep you updated.

**Comment by PhantomRay** [comment] 2021-12-21 09:02
Thank you very much @weyoss for your consideration!

**Comment by weyoss** [comment] 2022-01-03 18:00
Hey @PhantomRay,

> I believe your suggestion for producer.produce(queue, message, cb) is worth to be included in the next release roadmap in order to publish efficiently a message to multiple queues without creating multiple producer instances.

You should use MultiQueueProducer. See https://github.com/weyoss/redis-smq/blob/master/docs/api/multi-queue-producer.md

Don't forget to upgrade your RedisSMQ installation.

**Comment by PhantomRay** [comment] 2022-01-03 19:05
Nice! Just in time!

Happy New Year btw!

**Comment by weyoss** [comment] 2022-01-04 06:49
Happy new year :)

**Comment by weyoss** [comment] 2022-01-04 06:49
Closing as resolved.

**Closed by weyoss** 2022-01-04 06:49 UTC
Labels: question / feature request
