### ISSUE TITLE
Upgrade to Redis 4

### ISSUE THREAD

**Issue by PhilHannent** [weyoss/redis-smq#86] opened 2022-05-22 05:57 UTC
Good morning,

I'd like to request that the included Redis library be upgraded to version 4:
https://github.com/redis/node-redis

We're using this in our projects and it would be great if redis-smq also used the more recent version.

**Comment by weyoss** [comment] 2022-05-23 08:59
@PhilHannent Thank you for opening this issue.

This issue is a duplicate of https://github.com/weyoss/redis-smq/issues/78 which I have reopened and in which I have leaved there a couple of new comments.

 Redis may be upgraded to v4 in `redis-smq@v7` release, if such upgrade would not be costly.

**Comment by weyoss** [comment] 2022-05-30 18:18
Starting with v7.0.0-rc.4 pre-release, node-redis v4 is now supported. It was decided to keep support of node-redis v3 as it is still very popular and more stable than v4.

So as a result, RedisSMQ supports ioredis, nodis-redis v3, and node-redis v4.

**Comment by weyoss** [comment] 2022-05-30 18:58
@PhilHannent Please feel free to test it. If you encounter any issue do not hesitate to report it. 

Feedbacks are also welcome.

Keeping this issue open until v7 is ready for release.

**Comment by PhilHannent** [comment] 2022-06-03 09:05
Thank you for the update. We're on a bank holiday in the UK, I'll try and take a look at testing this in my project next week.

**Comment by weyoss** [comment] 2022-06-18 20:00
Closing as resolved.

**Closed by weyoss** 2022-06-18 20:00 UTC
Labels: feature request
